// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BoundingPoly A bounding polygon for the detected image annotation.
// swagger:model BoundingPoly
type BoundingPoly struct {

	// The bounding polygon vertices.
	Vertices []*Vertex `json:"vertices,omitempty"`
}

// Validate validates this bounding poly
func (m *BoundingPoly) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVertices(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BoundingPoly) validateVertices(formats strfmt.Registry) error {

	if swag.IsZero(m.Vertices) { // not required
		return nil
	}

	for i := 0; i < len(m.Vertices); i++ {

		if swag.IsZero(m.Vertices[i]) { // not required
			continue
		}

		if m.Vertices[i] != nil {

			if err := m.Vertices[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vertices" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BoundingPoly) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BoundingPoly) UnmarshalBinary(b []byte) error {
	var res BoundingPoly
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
