// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TextProperty Additional information detected on the structural component.
// swagger:model TextProperty
type TextProperty struct {

	// Detected start or end of a text segment.
	DetectedBreak *DetectedBreak `json:"detectedBreak,omitempty"`

	// A list of detected languages together with confidence.
	DetectedLanguages []*DetectedLanguage `json:"detectedLanguages,omitempty"`
}

// Validate validates this text property
func (m *TextProperty) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetectedBreak(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDetectedLanguages(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TextProperty) validateDetectedBreak(formats strfmt.Registry) error {

	if swag.IsZero(m.DetectedBreak) { // not required
		return nil
	}

	if m.DetectedBreak != nil {

		if err := m.DetectedBreak.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("detectedBreak")
			}
			return err
		}
	}

	return nil
}

func (m *TextProperty) validateDetectedLanguages(formats strfmt.Registry) error {

	if swag.IsZero(m.DetectedLanguages) { // not required
		return nil
	}

	for i := 0; i < len(m.DetectedLanguages); i++ {

		if swag.IsZero(m.DetectedLanguages[i]) { // not required
			continue
		}

		if m.DetectedLanguages[i] != nil {

			if err := m.DetectedLanguages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("detectedLanguages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TextProperty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TextProperty) UnmarshalBinary(b []byte) error {
	var res TextProperty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
