// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/marshome/p-vision/api/receipt/server/models"
)

// NewReceiptsExtractParams creates a new ReceiptsExtractParams object
// with the default values initialized.
func NewReceiptsExtractParams() ReceiptsExtractParams {
	var ()
	return ReceiptsExtractParams{}
}

// ReceiptsExtractParams contains all the bound params for the receipts extract operation
// typically these are obtained from a http.Request
//
// swagger:parameters receipts_extract
type ReceiptsExtractParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: header
	*/
	AccessControlAllowOrigin *string
	/*Request
	  Required: true
	  In: body
	*/
	Body *models.ReceiptExtractRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ReceiptsExtractParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := o.bindAccessControlAllowOrigin(r.Header[http.CanonicalHeaderKey("Access-Control-Allow-Origin")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ReceiptExtractRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ReceiptsExtractParams) bindAccessControlAllowOrigin(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.AccessControlAllowOrigin = &raw

	return nil
}
