// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ReceiptsReportOKCode is the HTTP code returned for type ReceiptsReportOK
const ReceiptsReportOKCode int = 200

/*ReceiptsReportOK ok

swagger:response receiptsReportOK
*/
type ReceiptsReportOK struct {
}

// NewReceiptsReportOK creates ReceiptsReportOK with default headers values
func NewReceiptsReportOK() *ReceiptsReportOK {
	return &ReceiptsReportOK{}
}

// WriteResponse to the client
func (o *ReceiptsReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// ReceiptsReportBadRequestCode is the HTTP code returned for type ReceiptsReportBadRequest
const ReceiptsReportBadRequestCode int = 400

/*ReceiptsReportBadRequest invalid arguments

swagger:response receiptsReportBadRequest
*/
type ReceiptsReportBadRequest struct {
}

// NewReceiptsReportBadRequest creates ReceiptsReportBadRequest with default headers values
func NewReceiptsReportBadRequest() *ReceiptsReportBadRequest {
	return &ReceiptsReportBadRequest{}
}

// WriteResponse to the client
func (o *ReceiptsReportBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
