// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ReceiptsExtractHandlerFunc turns a function with the right signature into a receipts extract handler
type ReceiptsExtractHandlerFunc func(ReceiptsExtractParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ReceiptsExtractHandlerFunc) Handle(params ReceiptsExtractParams) middleware.Responder {
	return fn(params)
}

// ReceiptsExtractHandler interface for that can handle valid receipts extract params
type ReceiptsExtractHandler interface {
	Handle(ReceiptsExtractParams) middleware.Responder
}

// NewReceiptsExtract creates a new http.Handler for the receipts extract operation
func NewReceiptsExtract(ctx *middleware.Context, handler ReceiptsExtractHandler) *ReceiptsExtract {
	return &ReceiptsExtract{Context: ctx, Handler: handler}
}

/*ReceiptsExtract swagger:route POST /receipts_extract receiptsExtract

Receipt extract

*/
type ReceiptsExtract struct {
	Context *middleware.Context
	Handler ReceiptsExtractHandler
}

func (o *ReceiptsExtract) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReceiptsExtractParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
