// Code generated by go-swagger; DO NOT EDIT.

/*Package restapi Mars receipt

    Schemes:
      http
    Host: localhost
    BasePath: /api/receipt/v1
    Version: v1
    Contact: mars

    Consumes:
    - application/json


    Produces:
    - application/json


swagger:meta
*/
package restapi
