// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReceiptReportRequest receipt report request
// swagger:model ReceiptReportRequest
type ReceiptReportRequest struct {

	// Text annotation
	// Required: true
	FullTextAnnotation *TextAnnotation `json:"fullTextAnnotation"`

	// The image
	// Required: true
	Image *Image `json:"image"`

	// Receipt info
	// Required: true
	ReceiptInfo *ReceiptInfo `json:"receiptInfo"`
}

// Validate validates this receipt report request
func (m *ReceiptReportRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFullTextAnnotation(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateImage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateReceiptInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReceiptReportRequest) validateFullTextAnnotation(formats strfmt.Registry) error {

	if err := validate.Required("fullTextAnnotation", "body", m.FullTextAnnotation); err != nil {
		return err
	}

	if m.FullTextAnnotation != nil {

		if err := m.FullTextAnnotation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fullTextAnnotation")
			}
			return err
		}
	}

	return nil
}

func (m *ReceiptReportRequest) validateImage(formats strfmt.Registry) error {

	if err := validate.Required("image", "body", m.Image); err != nil {
		return err
	}

	if m.Image != nil {

		if err := m.Image.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("image")
			}
			return err
		}
	}

	return nil
}

func (m *ReceiptReportRequest) validateReceiptInfo(formats strfmt.Registry) error {

	if err := validate.Required("receiptInfo", "body", m.ReceiptInfo); err != nil {
		return err
	}

	if m.ReceiptInfo != nil {

		if err := m.ReceiptInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("receiptInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReceiptReportRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReceiptReportRequest) UnmarshalBinary(b []byte) error {
	var res ReceiptReportRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
