// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/marshome/p-receipt/api/receipt/client/models"
)

// NewReceiptsReportParams creates a new ReceiptsReportParams object
// with the default values initialized.
func NewReceiptsReportParams() *ReceiptsReportParams {
	var ()
	return &ReceiptsReportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReceiptsReportParamsWithTimeout creates a new ReceiptsReportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReceiptsReportParamsWithTimeout(timeout time.Duration) *ReceiptsReportParams {
	var ()
	return &ReceiptsReportParams{

		timeout: timeout,
	}
}

// NewReceiptsReportParamsWithContext creates a new ReceiptsReportParams object
// with the default values initialized, and the ability to set a context for a request
func NewReceiptsReportParamsWithContext(ctx context.Context) *ReceiptsReportParams {
	var ()
	return &ReceiptsReportParams{

		Context: ctx,
	}
}

// NewReceiptsReportParamsWithHTTPClient creates a new ReceiptsReportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReceiptsReportParamsWithHTTPClient(client *http.Client) *ReceiptsReportParams {
	var ()
	return &ReceiptsReportParams{
		HTTPClient: client,
	}
}

/*ReceiptsReportParams contains all the parameters to send to the API endpoint
for the receipts report operation typically these are written to a http.Request
*/
type ReceiptsReportParams struct {

	/*Body
	  Request

	*/
	Body *models.ReceiptReportRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the receipts report params
func (o *ReceiptsReportParams) WithTimeout(timeout time.Duration) *ReceiptsReportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the receipts report params
func (o *ReceiptsReportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the receipts report params
func (o *ReceiptsReportParams) WithContext(ctx context.Context) *ReceiptsReportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the receipts report params
func (o *ReceiptsReportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the receipts report params
func (o *ReceiptsReportParams) WithHTTPClient(client *http.Client) *ReceiptsReportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the receipts report params
func (o *ReceiptsReportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the receipts report params
func (o *ReceiptsReportParams) WithBody(body *models.ReceiptReportRequest) *ReceiptsReportParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the receipts report params
func (o *ReceiptsReportParams) SetBody(body *models.ReceiptReportRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ReceiptsReportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.ReceiptReportRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
