// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/marshome/p-receipt/api/receipt/client/models"
)

// ReceiptsExtractReader is a Reader for the ReceiptsExtract structure.
type ReceiptsExtractReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReceiptsExtractReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReceiptsExtractOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewReceiptsExtractBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewReceiptsExtractInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReceiptsExtractOK creates a ReceiptsExtractOK with default headers values
func NewReceiptsExtractOK() *ReceiptsExtractOK {
	return &ReceiptsExtractOK{}
}

/*ReceiptsExtractOK handles this case with default header values.

Response
*/
type ReceiptsExtractOK struct {
	/*cors
	 */
	AccessControlAllowOrigin string

	Payload *models.ReceiptExtractResponse
}

func (o *ReceiptsExtractOK) Error() string {
	return fmt.Sprintf("[POST /receipts_extract][%d] receiptsExtractOK  %+v", 200, o.Payload)
}

func (o *ReceiptsExtractOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	o.Payload = new(models.ReceiptExtractResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReceiptsExtractBadRequest creates a ReceiptsExtractBadRequest with default headers values
func NewReceiptsExtractBadRequest() *ReceiptsExtractBadRequest {
	return &ReceiptsExtractBadRequest{}
}

/*ReceiptsExtractBadRequest handles this case with default header values.

invalid argument
*/
type ReceiptsExtractBadRequest struct {
	Payload string
}

func (o *ReceiptsExtractBadRequest) Error() string {
	return fmt.Sprintf("[POST /receipts_extract][%d] receiptsExtractBadRequest  %+v", 400, o.Payload)
}

func (o *ReceiptsExtractBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReceiptsExtractInternalServerError creates a ReceiptsExtractInternalServerError with default headers values
func NewReceiptsExtractInternalServerError() *ReceiptsExtractInternalServerError {
	return &ReceiptsExtractInternalServerError{}
}

/*ReceiptsExtractInternalServerError handles this case with default header values.

internal
*/
type ReceiptsExtractInternalServerError struct {
	Payload string
}

func (o *ReceiptsExtractInternalServerError) Error() string {
	return fmt.Sprintf("[POST /receipts_extract][%d] receiptsExtractInternalServerError  %+v", 500, o.Payload)
}

func (o *ReceiptsExtractInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
